name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run exercice_4 test with unittest
        run: python exercice_4/test.py
      - name: Run exercices_1_2_3 test with unittest
        run: python exercices_1_2_3/tests.py
        #run: python -m unittest